name: build

on:
  push:
    branches: [ main ]
    tags: ['*']
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build and install cc65 components
        run: >
          git clone https://github.com/cc65/cc65 /tmp/cc65 &&
          sudo make -C /tmp/cc65 ca65 ld65 avail &&
          ca65 --version

      - name: build and install cadius
        run: >
          git clone https://github.com/mach-kernel/cadius /tmp/cadius &&
          make -C /tmp/cadius &&
          sudo make -C /tmp/cadius install

      - name: build
        env:
          TERM: xterm-256color
        run: >
          make && make package

      - name: deploy new version
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1.8.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "out/prodos-path.po"
